### ISSUE TITLE
Attempting to save User Group changes against a whole XProfile Field Group doesn't work

### ISSUE THREAD

**Issue by davidpagepsycle** [lmoffereins/bp-xprofile-for-user-groups#3]
Tracked it down to this line https://github.com/lmoffereins/bp-xprofile-for-user-groups/blob/master/bp-xprofile-for-user-groups.php#L795 within fieldgroup_save_metabox() which has `==` rather than `!=` as field_save_metabox() has ( https://github.com/lmoffereins/bp-xprofile-for-user-groups/blob/master/bp-xprofile-for-user-groups.php#L898 ).

Changing this line causes it to work as expected.

**Comment by lmoffereins** [comment]
Hi David, 
Thank you for bringing this issue to my attention. Version 1.1.2 contains the fix for this issue. 
Also, thanks for using my plugin.
